version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: studypath-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: studypath
      POSTGRES_USER: studypath_user
      POSTGRES_PASSWORD: studypath_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U studypath_user -d studypath']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
